# Generated by Django 2.2 on 2021-03-02 03:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_auto_20210118_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
