# Generated by Django 2.2 on 2021-03-04 23:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_auto_20210301_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date_modified', '-date_created']},
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
