# Generated by Django 2.2 on 2021-03-05 02:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_auto_20210304_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
