# Generated by Django 2.2 on 2021-03-05 23:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0006_auto_20210304_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
