# Generated by Django 2.2 on 2021-03-18 23:46

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0007_auto_20210305_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
