# Generated by Django 2.2 on 2021-03-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0008_auto_20210318_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
