# Generated by Django 2.2 on 2021-05-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ersatznoteuser',
            name='username',
        ),
    ]
